services:
  pelacli:
    container_name: pelacli
    image: pelagosnetwork/pelacli:latest
    working_dir: /app
    volumes:
      - ./data:/data
      - ./pelacli.yaml:/config/pelacli.yaml:ro
    ports:
      - "8081:8081"
    command:
      - consensus
      - --config=/config/pelacli.yaml

  appchain:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    pid: "service:pelacli"
    image: appchain:latest
    volumes:
      - ./data:/data
      - ./config.yaml:/config/config.yaml:ro
    ports:
      - "9090:9090"
      - "8080:8080"
    depends_on:
      - pelacli
    command:
      - -config=/config/config.yaml

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    depends_on:
      - appchain

  explorer:
    image: pelagosnetwork/explorer:latest
    ports:
      - "3001:3000"
    environment:
      - RPC_URL=http://localhost:8080/rpc
      - EXTERNAL_RPC_URL=http://localhost:8081/rpc
    depends_on:
      - appchain
      - pelacli

